
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/lojaPocoes
    username: postgres
    password: CBritoDev2025!

  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: never

